### ISSUE TITLE
Niet zo volgens BEM

### ISSUE THREAD

**Issue by Theo-denBlanken** [markdooremaal/BEM_Opdracht#2]
```
<div class="social">
    <a href="#" class="fontawesome__icon fontawesome__icon--train"></a>
    <a href="#" class="fontawesome__icon fontawesome__icon--boat"></a>
    <a href="#" class="fontawesome__icon fontawesome__icon--bus"></a>
  </div>
```
het blok heeft class `social` dan hebben de elemeneten daarbinnen toch een class `social__icon` en `social__icon--train`. 
Immers het **B**lok noem je social en het a-element is het **E**lement en daar zijn 3 modifiers!!

**Comment by markdooremaal** [comment]
Fixed!
